networks:
  dev:
    driver: bridge

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      #- '/etc/letsencrypt:/etc/letsencrypt'
    depends_on:
      - backend
      - frontend
    networks:
      - dev

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"  # Пробрасываем порт для доступа с хоста
    networks:
      - dev
    environment:
      - DJANGO_SETTINGS_MODULE=site_project.settings
      - PYTHONUNBUFFERED=1
    volumes:
      - ./staticfiles:/app/staticfiles

  frontend:
    build:
      context: ./frontend
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"  # Для прямого доступа при отладке
    networks:
      - default
  # Порт не пробрасываем - доступ через nginx