# Generated by Django 4.2.16 on 2025-08-10 15:08

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import otp_app.managers
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(default=False, max_length=50)),
                ('second_name', models.CharField(default=False, max_length=50)),
                ('last_name', models.CharField(default=False, max_length=50)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(16)])),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=False, max_length=10)),
                ('blood_type', models.CharField(choices=[('I', 'first'), ('II', 'second'), ('III', 'third'), ('IV', 'fourth')], default=False, max_length=10)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('otp_mode', models.BooleanField(default=False)),
                ('otp_verified', models.BooleanField(default=False)),
                ('otp_validate', models.BooleanField(default=False)),
                ('otp_base32', models.CharField(max_length=255, null=True)),
                ('otp_auth_url', models.CharField(max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', otp_app.managers.UserManager()),
            ],
        ),
    ]
